name: test
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: install tools
      run: sudo apt-get -yq update && sudo apt-get -yq install clang-format
    - name: clang-format
      run: clang-format --style llvm src/*.[ch]
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: build test
      run: ./scripts/build.sh
